profiles:
  coverage_weighted:
    alpha: 0.5
    min_shared_features: 2
    features:
      domain_string:
        weight: 1.0
        coverage_rate: 1.0
        enabled: true
      registration_time:
        weight: 1.0
        coverage_rate: 0.2464
        enabled: true
      tls_certificate:
        weight: 1.0
        coverage_rate: 0.3543
        enabled: true
      jarm:
        weight: 1.0
        coverage_rate: 0.0
        enabled: true
      favicon:
        weight: 1.0
        coverage_rate: 0.0468
        enabled: true
      passive_dns:
        weight: 1.0
        coverage_rate: 0.9371
        enabled: true
      asn_geo:
        weight: 1.0
        coverage_rate: 0.7266
        enabled: true
