coverage_stats:
  generated_at: '2026-05-01T20:33:11.913972+00:00'
  source_dir: data/enrichment
  total_domains: 938
  skipped_files: 0
  features:
    domain_string:
      count: 938
      rate: 1.0
    registration_time:
      count: 498
      rate: 0.5309
    tls_certificate:
      count: 360
      rate: 0.3838
    jarm:
      count: 0
      rate: 0.0
    favicon:
      count: 49
      rate: 0.0522
    passive_dns:
      count: 897
      rate: 0.9563
    asn_geo:
      count: 730
      rate: 0.7783
